### ISSUE TITLE
Fix travis

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/truebit-os#18]
Tests pass locally, but seem to fail on travis.

Have a hunch it is related to #17 

The other guess is that the timeouts are not being respected (which doesn't make sense).

**Comment by OR13** [comment]
@hswick I think this is related to versions of truffle / ganache.

**Comment by hswick** [comment]
I shouldve specified which tests are failing. It was the os-challenge test that was failing on Travis, but I had working on my machine.

I'll just merge latest changes with my wasm fork, and add the challenge test again and see if that fixes it.

**Comment by hswick** [comment]
Travis is testing wasm-client now
