### ISSUE TITLE
deploy.sh fails with older truffle version

### ISSUE THREAD

**Issue by hobofan** [TrueBitFoundation/truebit-os#19]
```
Error parsing /Users/hobofan/stuff/truebit/truebit-os/basic-client/incentive-layer/contracts/DepositsManager.sol: ParsedContract.sol:16:16: ParserError: Expected identifier, got 'LParen'
    constructor() public {
               ^
Compilation failed. See above.
```

I got this error when following the instructions from the README and running `deploy.sh`. I noticed that the global install of truffle is used to run the migrations. Upgrading to a newer truffle version works, but depending on having the correct truffle version installed globally seems like it would something to break very easily in the future.

@hswick Shouldn't `incentive-layer` and `dispute-resolution-layer` bring their own truffle versions with them and then use those to run the migrations? I saw that you recently removed the truffle dependency from `incentive-layer`. Is there any specific reason for that?

**Comment by hswick** [comment]
@hobofan I agree that it might be better to provide the truffle versions by the dependencies. I removed it because it was an outdated version I believe.

More than happy to accept PRs to fix this.

**Comment by hobofan** [comment]
> More than happy to accept PRs to fix this.

Will do! :)

**Comment by hswick** [comment]
I've included the updates. Feel free to reopen if you have any issues.
