### ISSUE TITLE
Add ipfs daemon to Travis

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/truebit-os#25]
test/os-wasm-ipfs.js requires IPFS to be running. Need IPFS to be running in travis env in order to run the test in travis as well

**Comment by hswick** [comment]
Currently travis does not test os usage of ipfs. After adding ipfs to travis need to include tests for os-wasm-ipfs.js, os-wasm-alphabet.js, and os-wasm-alphabet-challenge.js

**Comment by OR13** [comment]
I can do this.

**Comment by OR13** [comment]
in progress.

**Comment by OR13** [comment]
This can be closed now i think.
