### ISSUE TITLE
Logging system

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/truebit-os#3]
Passing in a logger to the processes would be nice, and if it wrote to an actual logs file

**Comment by hswick** [comment]
@OR13 that would be awesome. I'd be happy to see your approach.

**Comment by hswick** [comment]
@OR13 you can go ahead and logging to the rest of the code if you want now.

**Comment by OR13** [comment]
hey, sorry for missing this. 

There are a number of logging levels we can use, which can then be used to make the logs noisy or quiet as we choose.

https://github.com/winstonjs/winston#logging-levels

```
{ 
  emerg: 0, 
  alert: 1, 
  crit: 2, 
  error: 3, 
  warning: 4, 
  notice: 5, 
  info: 6, 
  debug: 7
}
```

I will add logging sparingly to any work from now on, if you want to see more, just ask. I don't want to add so much it become too distracting.

**Comment by hswick** [comment]
Good to know. I think for now we can get away with mostly just info
