### ISSUE TITLE
Add smart contract unit tests

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/truebit-os#35]
On #33 

Smart contracts for `incentive` and `dispute` have been moved into `wasm-client/contracts`. However, I have not added the relevant unit tests for those smart contracts.

We need to add these tests to the `test` directory

**Comment by OR13** [comment]
main challenge here is those modules rely on truffle and truebit-os does not.

**Comment by OR13** [comment]
in progress.

**Comment by hswick** [comment]
Most of this has been resolved with #84 will open another issue with more specifics
