### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/truebit-os#55]
We should add a simple docker file with instructions on README to build truebit-os inside of Docker

**Comment by gjgd** [comment]
Seconded. There is a Dockerfile that contains commands to run, but they are not sufficient to be able to run the test. 
A separate .md file, or an entry in the README for "Docker install" containing step by step instructions to be able to run the project with Docker would be super useful

**Comment by hswick** [comment]
Hi @gjgd, apologies for the lack of docs for the Dockerfile. We just merged it in yesterday.

**Comment by hswick** [comment]
README includes installation instructions after https://github.com/TrueBitFoundation/truebit-os/commit/1b48c78e01f4abf2056a7bca78a1ca85e5cf552a
