### ISSUE TITLE
Running task without specifying task file in CLI gives weird error message

### ISSUE THREAD

**Issue by hswick** [TrueBitFoundation/truebit-os#63]
I'm glad that an error message is given when I don't specify `-t` in the command. But this is what happens:

```
🎲   $ task -a 0
Error: ENOENT: no such file or directory, open 'testTask.json'
```

So instead of trying to open undefined it opened 'testTask.json'. I'm assuming this is a default argument somewhere, but it should be changed.

**Comment by mrsmkl** [comment]
I think I changed this to a new default value.
